force-app/main/default/objects/Referral_Source__c/Referral_Source__c.object-meta.xml
<CustomObject>
    <label>Referral Source</label>
    <nameField>
        <label>Referral Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Referral Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Referral_Source__c/fields/Province_State__c.field-meta.xml
<CustomField>
    <fullName>Province_State__c</fullName>
    <label>Province/State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Source__c/fields/Referral_Source_Phone__c.field-meta.xml
<CustomField>
    <fullName>Referral_Source_Phone__c</fullName>
    <description>The work phone number of this facility</description>
    <label>Referral Source Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referral_Source__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <inlineHelpText>Street name</inlineHelpText>
    <label>Street</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referral_Source__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <description>Referral Source&apos;s Zip or Postal Code</description>
    <label>Zip/Postal Code</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReferralSourceModel.cls
// Referral source entry wizard model


public class ReferralSourceModel {
    
    @AuraEnabled
    public String street{get;set;}
    @AuraEnabled
    public String city{get;set;}
    @AuraEnabled
    public String province{get;set;}
    @AuraEnabled
    public String name{get;set;}
    @AuraEnabled
    public String country{get;set;}
    @AuraEnabled
    public String phoneNumber{get;set;}
    @AuraEnabled
    public String postalCode{get;set;}


    public  static Referral_Source__c ToReferralSourceRecord(ReferralSourceModel source){
        System.debug(source);

    
        return new Referral_Source__c(
                                        Name=source.name , 
                                        Referral_Source_Phone__c = source.phoneNumber,
                                        City__c = source.city, 
                                        Street__c = source.street,
                                        Country__c = source.country,
                                        Province_State__c = source.province,
                                        Zip_Postal_Code__c = source.postalCode
                                        );
                                        
    }
    

    public ReferralSourceModel FromReferralSourceRecord(){
        throw new UnimplementedException('method not implented');
    }



    public class UnimplementedException extends Exception {}

}